# Generated by Django 5.1 on 2024-10-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_group_category_group_groupmembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
